# Generated by Django 5.1.4 on 2025-04-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="subscription_expiry",
            field=models.DateField(blank=True, null=True),
        ),
    ]
